project:
  type: website

website:
  title: "Parker Barnes"
  navbar:
  
    left: 
      - href: blog.qmd
        text: Blog
      - href: projects.qmd
        text: Projects
      - href: resume.qmd
        text: Resume
  
  
    right:
      - about.qmd
      - icon: github
        href: https://github.com/barnesparker
      - icon: twitter
        href: https://twitter.com/paRkeRuser1
format:
  html:
    theme: cosmo
    css: styles.css



