project:
  type: website

website:
  title: "Parker Barnes"
  navbar:
  
    left: 
      - href: index.qmd
        text: Blog
      - href: projects.qmd
        text: Projects
      - href: resume.qmd
        text: Resume
  
  
    right:
      - about.qmd
      - icon: github
        href: https://github.com/barnesparker
        
format:
  html:
    theme: cosmo
    css: styles.css
    
    
execute:
  freeze: auto



