project:
  type: website

website:
  title: "Parker Barnes"
  navbar:
    background: primary
    left: 
      - href: index.qmd
        text: Blog
      - href: projects.qmd
        text: Shiny Apps
      - href: resume.qmd
        text: Resume
  
  
    right:
      - about.qmd
      - icon: github
        href: https://github.com/barnesparker/tidy-tuesday-blog
        
format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    
execute:
  freeze: auto



